name: ci

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Next.js using teaxyz
        uses: teaxyz/setup@v0
        with:
          target: build