name: ci

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: echo $HOME
      - run: ls $HOME
      - run: ls -la ~/opt
      - name: Cache tea dependencies
        uses: actions/cache@v3
        with:
          path: ~/opt
          key: ${{ runner.os }}-tea-${{ hashFiles('**/README.md') }}
      - name: Build Next.js using teaxyz
        uses: teaxyz/setup@v0
        with:
          target: build